### ISSUE TITLE
FormHelper select multiple with checkboxes produces duplicate checkboxes

### ISSUE THREAD

**Issue by georgeconstantinou** [FriendsOfCake/bootstrap-ui#148] opened 2016-05-03 14:18 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 0.5.0
* Bootstrap Framework Version: 3.3.6
* jQuery: 2.1.4
* Platform and Target: CakePHP 3.2.8

### What you did
Following [CakePHP documentation](http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-select-pickers), this was added in the edit.ctp.
```php
$options = [
    'Value 1' => 'Label 1',
    'Value 2' => 'Label 2'
];

echo $this->Form->select('field', $options, ['multiple' => 'checkbox']);
```
If BootstrapUI FormHelper is not loaded the checkboxes appear correctly.

### Expected Behavior
A list of checkboxes with labels

### Actual Behavior
A list of **double** checkboxes with labels

![fireshot capture 29 - roles_ - http___localhost_8010_roles-capabi](https://cloud.githubusercontent.com/assets/1926811/14985928/6cf8381c-1152-11e6-9c7d-e3be67d7507e.png)

**Comment by mamchenkov** [comment] 2016-05-10 10:06
Do you guys need any more info on this?

**Comment by dereuromark** [comment] 2016-05-10 10:10
The outputted raw HTML in general would also be nice, and if you have an idea of a fix this could speed up the process I think.

**Comment by georgeconstantinou** [comment] 2016-05-11 10:15
**HTML output**
```html
<div class="checkbox">
    <label>
        <input type="checkbox" name="field[]" value="Value 1" id="field-value-1">
        <label for="field-value-1">
            <input type="checkbox" name="field[]" value="Value 1" id="field-value-1">Label 1</label>
    </label>
</div>
<div class="checkbox">
    <label>
        <input type="checkbox" name="field[]" value="Value 2" id="field-value-2">
        <label for="field-value-2">
            <input type="checkbox" name="field[]" value="Value 2" id="field-value-2">Label 2</label>
    </label>
</div>
````

**Comment by dereuromark** [comment] 2016-05-12 00:02
Seems like only the select() one is affected, input() is OK:

    echo $this->Form->input('field', ['options' => $options, 'multiple' => 'checkbox']);

outputs the expected result.

**Comment by dereuromark** [comment] 2016-05-26 12:06
Does anyone have an idea for a fix for this?

**Comment by cjquinn** [comment] 2016-06-08 17:35
You can replicate this with `input()` if you use `'type' => 'multicheckbox'`. I think the `checkboxWrapper` template can just be removed at least that fixes the issue for me. The problem seems to be that `{{label}}` that is being passed already has the input wrapped in it so when it is applied to the following template you get 2 inputs `<div class="checkbox"><label>{{input}}{{label}}</label></div>`.

**Comment by dereuromark** [comment] 2016-09-22 19:43
I could reproduce and removing that invalid template indeed fixed the issue. 
Thanks for reporting!

**Closed by dereuromark** 2016-09-22 19:43 UTC
Labels: bug

**Comment by mamchenkov** [comment] 2016-09-23 11:59
:+1: Thanks for the fix :smile:
