### ISSUE TITLE
Bootstrap 3 and 4 in the same project

### ISSUE THREAD

**Issue by jorisvaesen** [FriendsOfCake/bootstrap-ui#264] opened 2019-02-18 12:14 UTC
We are currently migrating a big project from bootstrap 3 to bootstrap 4 but we are facing the problem that we can't install version ^1.4 and 2.0.0-beta4 of this plugin at the same time (same namespace).

How could we solve this to allow developers to migrate their projects in pieces? Could there be a repo for bootstrap 4 with a different namespace so composer could install both versions?

**Comment by ADmad** [comment] 2019-02-18 12:18
Duplicate of #212

**Closed by ADmad** 2019-02-18 12:18 UTC
