### ISSUE TITLE
Radio buttons do not work with horizontal layout.

### ISSUE THREAD

**Issue by gunner1095** [FriendsOfCake/bootstrap-ui#65] opened 2015-06-21 16:10 UTC
Radio buttons are not displayed correctly with horizontal layout.

Example:
```
$this->Form->create($user, ['align' => [
    'sm' => [
        'left' => 6,
        'middle' => 6,
        'right' => 12
    ],
    'md' => [
        'left' => 4,
        'middle' => 4,
        'right' => 4
    ]
]]); 

echo $this->Form->input('group_id', ['type' => 'radio', 'options' => ['Admin', 'User']]);

```

Produces this code:

```
<div class="form-group">
  <div class="col-sm-offset-6 col-md-offset-4 col-sm-6 col-md-4">
    <div class="radio">
      <label class="control-label col-sm-6 col-md-4">Group</label>
    </div>
  </div>
</div>
```

Running the same code with bootstrap-ui form helper disabled will produce the correct HTML:

```
    public $helpers = [
        'Html' => ['className' => 'BootstrapUI.Html'],
        //'Form' => ['className' => 'BootstrapUI.Form'],
        'Flash' => ['className' => 'BootstrapUI.Flash'],
        'Paginator' => ['className' => 'BootstrapUI.Paginator'],
    ];
```

```
<div class="input radio">
  <label>Group</label><input type="hidden" name="group_id" value="">
  <label for="group-id-0">
    <input type="radio" name="group_id" value="0" id="group-id-0">Admin
  </label>
  <label for="group-id-1">
    <input type="radio" name="group_id" value="1" id="group-id-1">User
  </label>
</div>
```

Is there a way to get bootstrap-ui to render radio buttons correctly within horizontal layouts?

**Comment by ADmad** [comment] 2015-06-21 16:12
Duplicate of #64

**Closed by ADmad** 2015-06-21 16:12 UTC
